version: "3.9"

services:
  trainer:
    image: mood-trainer
    container_name: mood-trainer
    volumes:
      - ./artifacts:/app/artifacts
    restart: "no"

  inference:
    image: mood-inference
    container_name: mood-inference
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
    depends_on:
      - trainer
